import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import { Product, FooterBanner, HeroBanner, Footer } from '../components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>A Modern Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <HeroBanner />


    <div className='products-heading'>
      <h2>Best selling products in the market
        <p>Devices of many variations</p>
      </h2>
    </div>

    <div className='products-container'>
      {['Product 1', 'Product 2'].map(
        (product) => product
      )}
    </div>


      <Footer />
    </>
  )
}
